### ISSUE TITLE
Missing REM Values in Customizer

### ISSUE THREAD

**Issue by zackeryfretty** [MapSteps/Page-Builder-Framework#47] opened 2024-05-28 13:54 UTC
It's a relatively minor annoyance but it seems any location where I was using REM in customizer after upgrading no longer shows a value:

![Screenshot 2024-05-28 at 9 46 30 AM](https://github.com/mapsteps/page-builder-framework/assets/4997906/f0c0e77e-5d62-4cdb-b163-a59cadb0d8d3)

What I had configured is still reflected correctly on the frontend though:

![Screenshot 2024-05-28 at 9 50 42 AM](https://github.com/mapsteps/page-builder-framework/assets/4997906/e229bbc9-ed9c-4f51-8878-678079bda870)

There's some sort of odd behavior when you try to do and sort of partial values specifically in the inputs:

I'm trying to type 2.5 here and as you can see the validation isn't letting it happen:

![Screen Capture on 2024-05-28 at 09-54-01](https://github.com/mapsteps/page-builder-framework/assets/4997906/b1bb4068-454e-425a-ad6c-1c83bf9e10dc)

Starts just adding a bunch of . toward the end.

**Comment by mapsteps** [comment] 2024-05-28 17:46
Hey @zackeryfretty,

the issue is confirmed, we're going to provide a fix asap :)

**Comment by zackeryfretty** [comment] 2024-05-28 19:28
Thanks & Sorry for filing so many of these the last few days, I've got a ton running on WPBF so I just keep finding the issues quick...😅

**Comment by mapsteps** [comment] 2024-06-03 11:40
This should now be fixed in version 2.11.0.7 :)

**Closed as completed by mapsteps** 2024-06-03 11:40 UTC
